void CL(char *color){
    if(color=="AirForceBlue")       CL_opr(0x5D8AA8);
    if(color=="AliceBlue")          CL_opr(0xF0F8FF);
    if(color=="Aqua")               CL_opr(0x00FFFF);
    if(color=="ArmyGreen")          CL_opr(0x4B5320);
    if(color=="Blond")              CL_opr(0xFAF0BE);
    if(color=="Blue")               CL_opr(0x0000FF);
    if(color=="BondiBlue")          CL_opr(0x0095B6);
    if(color=="BostonUniversityRed")CL_opr(0xCC0000);
    if(color=="Bronze")             CL_opr(0xCD7F32);
    if(color=="Brown")              CL_opr(0x964B00);
    if(color=="Carrot")             CL_opr(0xED9121);
    if(color=="Chartreuse")         CL_opr(0x7FFF00);
    if(color=="Chocolate")          CL_opr(0xD2691E);
    if(color=="Cobalt")             CL_opr(0x0047AB);
    if(color=="Cream")              CL_opr(0xFFFDD0);
    if(color=="Darkblue")           CL_opr(0x00008B);
    if(color=="Darkbrown")          CL_opr(0x654321);
    if(color=="Darkgreen")          CL_opr(0x013220);
    if(color=="Darkpink")           CL_opr(0xE75480);
    if(color=="Darkteagreen")       CL_opr(0xBADBAD);
    if(color=="Deeppink")           CL_opr(0xFF1493);
    if(color=="Emerald")            CL_opr(0x1ED000);
    if(color=="Gold")               CL_opr(0xFFD700);
    if(color=="Gray")               CL_opr(0x808080);
    if(color=="Green")              CL_opr(0x00FF00);
    if(color=="Indigo")             CL_opr(0x4B0082);
    if(color=="Lemon")              CL_opr(0xFDE910);
    if(color=="Magenta")            CL_opr(0xFF00FF);
    if(color=="MintGreen")          CL_opr(0x98FF98);
    if(color=="OldGold")            CL_opr(0xCFB53B);
    if(color=="Olive")              CL_opr(0x808000);
    if(color=="Paleblue")           CL_opr(0xAFEEEE);
    if(color=="Palebrown")          CL_opr(0x987654);
    if(color=="Paleyellow")         CL_opr(0xF0DC82);
    if(color=="PineGreen")          CL_opr(0x01796F);
    if(color=="Pumpkin")            CL_opr(0xFF7518);
    if(color=="Red")                CL_opr(0xFF0000);
    if(color=="SafetyOrange")       CL_opr(0xFF9900);
    if(color=="SeaGreen")           CL_opr(0x2E8B57);
    if(color=="Silver")             CL_opr(0xC0C0C0);
    if(color=="TeaGreen")           CL_opr(0xD0F0C0);
    if(color=="Teal")               CL_opr(0x008080);
    if(color=="Tomato")             CL_opr(0xFF6347);
    if(color=="Vanilla")            CL_opr(0xF3E5AB);
    if(color=="Violet")             CL_opr(0x8B00FF);
    if(color=="Wheat")              CL_opr(0xF5DEB3);
    if(color=="White")              CL_opr(0xFFFFFF);
    if(color=="Yellow")             CL_opr(0xFFFF00);
};

void CL_opr(uint32_t color){
    strip.clear();
    for(int in=0;in<15;in++)
        strip.setPixelColor(in,color);
};